### ISSUE TITLE
stat: can't stat '/var/run/docker.sock': No such file or directory

### ISSUE THREAD

**Issue by perrefe** [willfarrell/docker-crontab#12]
Time ago I've built an image based on willfarrell/crontab which basically adds a config.json file and  openssh & rsync packages and works like a charm, until yesterday :(. Thats because I built another version of my extended image, with a minimal change in config.json, but this time, if the lastest ("the real latest") image is used, the container don't run giving the error:

```stat: can't stat '/var/run/docker.sock': No such file or directory```

The last "latest" image id, which works is aa079ab29c75

**Comment by andryfailli** [comment]
Me too, I'm facing the same issue

**Comment by lbngoc** [comment]
I think you should mount /var/docker/docker.sock to your container in `docker-compose.yml`
```
version: "3"

services:
  crontab:
    build: .
    restart: always
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - "./config.json:/opt/crontab/config.json:rw"
```
