### ISSUE TITLE
error starting on macOS

### ISSUE THREAD

**Issue by f3r3nc** [willfarrell/docker-crontab#17]
macOS version: 10.13.3 
docker version: Docker version 18.03.1-ce
docker-compose.yml:

```
version: "3"

services:
  crontab:
    image: willfarrell/crontab
    container_name: cron
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - "./config.json:/opt/crontab/config.json:rw"
```
`docker logs cron` gives
```
addgroup: gid '0' in use
```
on local machine
```ls -lah /var/run/docker.sock
lrwxr-xr-x  1 root  daemon    58B Apr 26 21:55 /var/run/docker.sock -> /Users/...
```

When using the actual socket instead of the symlink the error is still there.
