### ISSUE TITLE
Does not work with DOCKER_HOST

### ISSUE THREAD

**Issue by RoboMagus** [willfarrell/docker-crontab#46]
I'm using the configuration below, and it complains about docker.sock:
 ``` stat: can't stat '/var/run/docker.sock': No such file or directory ```

```yaml

  crontab:
    image: willfarrell/crontab
    container_name: crontab
    restart: unless-stopped
    depends_on:
      - socket-proxy
    networks:
      - socket-proxy
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
    volumes:
      - ./Volumes/crontab/logs:/var/log/crontab
      - ./Volumes/crontab/config:/opt/crontab

```

I suspect [line 262 of docker-entrypoint](https://github.com/willfarrell/docker-crontab/blob/main/docker-entrypoint#L262), as this function will be called, regardless of whether we want to talk to the docker socket or when providing a DOCKER_HOST.
