### ISSUE TITLE
Feature Request: run docker task as a different user

### ISSUE THREAD

**Issue by JamborJan** [willfarrell/docker-crontab#50]
## Problem
When executing a command inside a docker container, it is possible to specify a user. Some tasks require running with a specific user, e.g. the nextcloud fulltext search re-index job. For example:

```bash
docker exec -u www-data nextcloud php occ fulltextsearch:index
```

When I'm trying to add this job to `docker-crontab` like this to run it every night at 1:30h:

```yaml
- name: nextcloud-fulltext
  command: php occ fulltextsearch:index
  comment: re-indexing nextcloud fulltext search for documents
  container: nextcloud
  schedule: '30  1 * * *'
```

I get an error from the nextcloud container that I have to run the command as user `www-data`.

## Proposed solution
It would be great to be able to specify a user in `config.yml` which will be translated into a `docker run -u user` command in the generated `*.sh` file for the cronjob. I think this would solve this issue.

## Workaround
Right now I'm doing a workaround by scheduling a docker command running within the `docker-crontab` container which then executes a command within the nextcloud container.

```yaml
- name: nextcloud-fulltext
  command: docker exec -u www-data nextcloud php occ fulltextsearch:index
  comment: re-indexing nextcloud fulltext search for documents
  container: crontab
  schedule: '30  1 * * *'
```
This generates a `docker exec` command which then runs again a `docker exec` command but with specified user.

**Comment by Kelivan** [comment]
Use "dockerargs": "-u username".
As a result, the script will look like this:
```
for CONTAINER_NAME in $CONTAINERS; do
    docker exec -u username ${CONTAINER_NAME} command
done
```

**Comment by JamborJan** [comment]
Hey @Kelivan,

Thanks for your help, that did of course work. Just in case someone stumbles over this issue, this is the complete working example:

```yaml
- name: nextcloud-fulltext
  dockerargs: '-u 1000'
  command: php occ fulltextsearch:index
  comment: re-indexing nextcloud fulltext search for documents
  container: nextcloud
  schedule: '30  2 * * *'
```

This creates this script:

```bash
echo "Start Cronjob **nextcloud-fulltext** re-indexing nextcloud fulltext search for documents"
docker exec -u 1000 nextcloud php occ fulltextsearch:index
echo "End Cronjob **nextcloud-fulltext** re-indexing nextcloud fulltext search for documents"
```
