### ISSUE TITLE
dial unix /var/run/docker.sock: connect: permission denied

### ISSUE THREAD

**Issue by markqiu** [willfarrell/docker-crontab#9]
Start Cronjob **6691da1d-2ed8-4afb-aca8-cec94c5bf680** update stock
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.32/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

**Comment by willfarrell** [comment]
Is this related to #6?

**Comment by markqiu** [comment]
seems not to

**Comment by renanbr** [comment]
I think i'm facing the same problem (not sure if it's a config.json error from my part).

For exemple, I'm trying to run a hello world in a container using compose.

A minimal step to reproduce the problem is creating a `./docker-compose-file` file:

```yml
version: "2.1"

services:
  myapp:
    image: alpine:3.5
    restart: always
    command: "sh -c 'while :; do sleep 1; done'"

  crontab:
    image: willfarrell/crontab
    restart: always
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # - "/usr/bin/docker:/usr/bin/docker:ro"
     - "./config.json:/opt/crontab/config.json:rw"
```

a `./config.json` file:

```json
[{
    "project":"crontab",
    "container":"myapp",
    "schedule": "@every 1m",
    "command": "echo 'Hello world!'"
}]
```
then running

```
$ docker-compose up -d
Pulling myapp (alpine:3.5)...
3.5: Pulling from library/alpine
b1f00a6a160c: Pull complete
Digest: sha256:b007a354427e1880de9cdba533e8e57382b7f2853a68a478a17d447b302c219c
Status: Downloaded newer image for alpine:3.5
Creating crontab_crontab_1 ... 
Creating crontab_myapp_1 ... 
Creating crontab_crontab_1
Creating crontab_crontab_1 ... done
```

and I get

```
$ docker-compose logs
Attaching to crontab_myapp_1, crontab_crontab_1
crontab_1  | ##### crontab generation complete #####
crontab_1  | */1 * * * * /bin/bash /opt/crontab/jobs/667d733e-2de1-4471-bd8a-9488a5b447e4.sh
crontab_1  | ##### run commands with onstart #####
crontab_1  | crond -f
crontab_1  | Start Cronjob **667d733e-2de1-4471-bd8a-9488a5b447e4** null
crontab_1  | Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```
